start_time: !!str &start 2018-08-02
end_time: !!str &end 2025-04-01
train_end_time: !!str &tend 2023-12-31
valid_start_time: !!str &vstart 2024-01-01
valid_end_time: !!str &vend 2024-09-30
test_start_time: !!str &tstart 2024-10-01
# the instrument set
instruments: &ins ["BTCUSDT"]
# control gate keeping / DQN
meta_trigger:
  enabled: true
  checkpoint_path: ./checkpoints/meta_dqn.pt
  module_path: qlib_custom.meta_trigger.meta_dqn_policy
# begin simulator code
simulator:
  data_granularity: 60
  time_per_step: 60
  vol_limit: null
env:
  concurrency: 6
  parallel_mode: dummy
action_interpreter:
  class: CustomActionInterpreter
  module_path: qlib_custom.custom_action_interpreter
  kwargs:
    values: 16
    max_step: 24  
state_interpreter:
  class: FullHistoryStateInterpreter
  kwargs:
    data_dim: 20
    data_ticks: 24  # 24 = 1440 min / 60 min
    max_step: 24
    processed_data_provider:
      class: HandlerProcessedDataProvider
      kwargs:
        data_dir: ./data3/pickle/        
        feature_columns_today: ["$high", "$low", "$open", "$close", "$volume", "q10", "q50", "q90", "fg_index", "btc_dom", "momentum_5d", "momentum_10d", "volatility", "vol_scaled", "vol_rank", "spread", "abs_q50", "spread_thresh", "signal_thresh", "signal_tier"]
        feature_columns_yesterday: ["$high_1", "$low_1", "$open_1", "$close_1", "$volume_1", "q10", "q50", "q90", "fg_index", "btc_dom", "momentum_5d", "momentum_10d", "volatility", "vol_scaled", "vol_rank", "spread", "abs_q50", "spread_thresh", "signal_thresh", "signal_tier"]
        backtest: false
      module_path: qlib.rl.data.native
  module_path: qlib.rl.order_execution.interpreter
reward:
  class: HybridExecutionReward
  module_path: qlib_custom.custom_reward
  kwargs:
    weight_pa: 1.0
    weight_vwap: 0.5
    weight_pressure: 0.3
    weight_penalty: 1.0
    vwap_feature: "$vwap_3h"
    pressure_feature: "$vwap_pressure"
data:
  source:
    order_dir: ./data3/orders
    selected_order_dir: ./data3/selected_orders 
    feature_root_dir: ./data3/pickle/
    feature_columns_today: ["$close0", "$volume0", "$vwap_3h", "$vwap_6h", "$vwap_12h", "$vwap_diff_3h", "$vwap_diff_6h", "$vwap_diff_12h", "$vwap_pressure", "tier_confidence", "q10", "q50", "q90", "side"]
    feature_columns_yesterday: ["$close0", "$volume0", "$vwap_3h", "$vwap_6h", "$vwap_12h", "$vwap_diff_3h", "$vwap_diff_6h", "$vwap_diff_12h", "$vwap_pressure", "tier_confidence", "q10", "q50", "q90", "side"]
    total_time: 1440
    default_start_time_index: 0
    default_end_time_index: 1440
    proc_data_dim: 14
  num_workers: 0
  queue_size: 20
network:
  class: Recurrent
  module_path: qlib.rl.order_execution.network
policy:
  class: PPO  # PPO, DQN
  kwargs:
    lr: 0.0001
  module_path: qlib.rl.order_execution.policy
runtime:
  seed: 42
  use_cuda: false
trainer:
  max_epoch: 500
  repeat_per_collect: 10
  earlystop_patience: 50
  episode_per_collect: 5000
  batch_size: 1024
  val_every_n_epoch: 4
  checkpoint_path: ./outputs/ppo
  checkpoint_every_n_iters: 1
